### ISSUE TITLE
Set up SPA routing for Github Pages

### ISSUE THREAD

**Issue by arnavb** [InVisionAR/web-frontend#7]
As of now, Github pages doesn't properly handle SPA routing in history mode, but that can be fixed if the instructions in [this repository](https://github.com/rafgraph/spa-github-pages) are followed.

**Comment by heykc** [comment]
Heya, I'd be happy to work on this issue for you. I'd also love to get to know more about this project in general. ✌

**Comment by arnavb** [comment]
@heykc Sure, I'll assign it to you. Regarding more information, @shricharanks108 will probably contact you at some point.

**Comment by heykc** [comment]
If this is time sensitive I could start working on this soon. If it's not, could I hold out on the PR until after hacktoberfest begins? Totally cool with it either way!

**Comment by arnavb** [comment]
@heykc I think this issue is somewhat important to get fixed soon because of how important it is to the functioning of the website. So I'd prefer sooner rather than later. The other issues, such as, e.g, #11 are very large, so you can make progress on them, but don't really have any particular deadline.

**Comment by heykc** [comment]
Right on, I'll get on this now, then. Also thanks for that issue rec for hacktoberfest 👍
